import {
  Atom,
  BookOpen,
  Briefcase,
  Calculator,
  Database,
  DollarSign,
  GitBranch,
  Grid3x3,
  Link,
  Network,
  BarChart3,
  TrendingUp,
  FlaskConical,
  Brain,
  Lightbulb,
  Cpu,
  Globe,
  Shield,
  Server,
  Monitor,
  Cloud,
  Layers,
  ArrowUpDown,
  TreePine,
  Workflow,
  Binary,
  Sigma,
  CircleDot,
  Shuffle,
  FileCode,
  Presentation,
  Users,
  Target,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps non-technical tag names to Lucide icon components.
 * Used as a fallback when a tag doesn't have a Devicon mapping.
 *
 * Keys are normalized: lowercase, no spaces, no dots.
 */
export const lucideTagMap: Record<string, LucideIcon> = {
  // ── CS Fundamentals ────────────────────────────────────────────
  dsa: Network,
  "data-structures": Network,
  algorithms: GitBranch,
  "linked-list": Link,
  tree: TreePine,
  trees: TreePine,
  sorting: ArrowUpDown,
  graph: GitBranch,
  graphs: GitBranch,
  "binary-search": Binary,
  recursion: Shuffle,
  "dynamic-programming": Brain,
  oop: Layers,
  "object-oriented": Layers,
  "compiler-design": FileCode,
  "operating-system": Monitor,
  os: Monitor,
  "process-scheduling": Workflow,
  "memory-management": Server,

  // ── Academic ───────────────────────────────────────────────────
  physics: Atom,
  chemistry: FlaskConical,
  mathematics: Calculator,
  math: Calculator,
  calculus: Sigma,
  "linear-algebra": Grid3x3,
  statistics: BarChart3,
  economics: TrendingUp,
  business: Briefcase,
  marketing: Presentation,
  finance: DollarSign,
  "hr-management": Users,
  "human-resource": Users,

  // ── CS Theory ──────────────────────────────────────────────────
  dbms: Database,
  "database": Database,
  "schema-design": Database,
  normalization: Database,
  networking: Globe,
  "cyber-security": Shield,
  "information-security": Shield,
  "artificial-intelligence": Brain,
  "machine-learning": Cpu,
  "data-science": BarChart3,
  "web-development": Globe,
  "mobile-development": Layers,
  "cloud-computing": Cloud,
  devops: Workflow,
  git: GitBranch,
  linux: Monitor,

  // ── General ────────────────────────────────────────────────────
  research: BookOpen,
  presentation: Presentation,
  project: Target,
  teamwork: Users,
  innovation: Lightbulb,
  startup: Zap,
  general: CircleDot,
  other: CircleDot,
  misc: CircleDot,
  "study-group": Users,
  "exam-prep": BookOpen,
  "course-help": BookOpen,
};


