/**
 * Maps normalized technology/tag names to Devicon CSS class names.
 * Based on Devicon (https://devicon.dev/) — 500+ icons.
 *
 * Keys are normalized: lowercase, no spaces, no dots.
 * e.g. "Node.js" → "nodejs", "React" → "react"
 */
export const techMap: Record<string, string> = {
  // ── Languages ──────────────────────────────────────────────────
  c: "devicon-c-plain",
  cplusplus: "devicon-cplusplus-plain",
  "c++": "devicon-cplusplus-plain",
  cpp: "devicon-cplusplus-plain",
  csharp: "devicon-csharp-plain",
  "c#": "devicon-csharp-plain",
  java: "devicon-java-plain",
  javascript: "devicon-javascript-plain",
  js: "devicon-javascript-plain",
  typescript: "devicon-typescript-plain",
  ts: "devicon-typescript-plain",
  python: "devicon-python-plain",
  ruby: "devicon-ruby-plain",
  go: "devicon-go-plain",
  golang: "devicon-go-plain",
  rust: "devicon-rust-plain",
  swift: "devicon-swift-plain",
  kotlin: "devicon-kotlin-plain",
  dart: "devicon-dart-plain",
  php: "devicon-php-plain",
  scala: "devicon-scala-plain",
  elixir: "devicon-elixir-plain",
  haskell: "devicon-haskell-plain",
  lua: "devicon-lua-plain",
  perl: "devicon-perl-plain",
  r: "devicon-r-original",
  matlab: "devicon-matlab-plain",
  latex: "devicon-latex-original",
  tex: "devicon-tex-plain",
  sql: "devicon-mysql-plain",
  bash: "devicon-bash-plain",
  shell: "devicon-bash-plain",
  powershell: "devicon-powershell-plain",

  // ── Frontend Frameworks ────────────────────────────────────────
  react: "devicon-react-original",
  reactjs: "devicon-react-original",
  "react.js": "devicon-react-original",
  nextjs: "devicon-nextjs-plain",
  "next.js": "devicon-nextjs-plain",
  vuejs: "devicon-vuejs-plain",
  vue: "devicon-vuejs-plain",
  "vue.js": "devicon-vuejs-plain",
  nuxtjs: "devicon-nuxtjs-plain",
  nuxt: "devicon-nuxtjs-plain",
  angular: "devicon-angular-plain",
  angularjs: "devicon-angularjs-plain",
  svelte: "devicon-svelte-plain",
  solidjs: "devicon-solidjs-plain",
  preact: "devicon-preact-plain",
  gatsby: "devicon-gatsby-plain",
  astro: "devicon-astro-plain",
  htmx: "devicon-htmx-original",

  // ── CSS / Styling ──────────────────────────────────────────────
  css3: "devicon-css3-plain",
  css: "devicon-css3-plain",
  sass: "devicon-sass-original",
  scss: "devicon-sass-original",
  less: "devicon-less-plain-wordmark",
  tailwindcss: "devicon-tailwindcss-plain",
  tailwind: "devicon-tailwindcss-plain",
  bootstrap: "devicon-bootstrap-plain",
  materialui: "devicon-materialui-plain",
  mui: "devicon-materialui-plain",
  chakraui: "devicon-chakraui-plain",

  // ── Backend Frameworks ─────────────────────────────────────────
  nodejs: "devicon-nodejs-plain",
  node: "devicon-nodejs-plain",
  "node.js": "devicon-nodejs-plain",
  express: "devicon-express-original",
  nestjs: "devicon-nestjs-plain",
  nest: "devicon-nestjs-plain",
  django: "devicon-django-plain",
  flask: "devicon-flask-original",
  fastapi: "devicon-fastapi-plain",
  laravel: "devicon-laravel-plain",
  rails: "devicon-rails-plain",
  spring: "devicon-spring-plain",
  graphql: "devicon-graphql-plain",
  apollo: "devicon-apollographql-plain",

  // ── Databases ──────────────────────────────────────────────────
  mongodb: "devicon-mongodb-plain",
  mongo: "devicon-mongodb-plain",
  mongoose: "devicon-mongoose-original",
  postgresql: "devicon-postgresql-plain",
  postgres: "devicon-postgresql-plain",
  mysql: "devicon-mysql-plain",
  sqlite: "devicon-sqlite-plain",
  redis: "devicon-redis-plain",
  firebase: "devicon-firebase-plain",
  dynamodb: "devicon-dynamodb-plain",
  cassandra: "devicon-cassandra-plain",
  neo4j: "devicon-neo4j-plain",
  elasticsearch: "devicon-elasticsearch-plain",
  oracle: "devicon-oracle-original",
  mariadb: "devicon-mariadb-plain",
  supabase: "devicon-supabase-plain",
  prisma: "devicon-prisma-original",

  // ── DevOps / Cloud ─────────────────────────────────────────────
  docker: "devicon-docker-plain",
  kubernetes: "devicon-kubernetes-plain",
  aws: "devicon-amazonwebservices-original",
  amazonwebservices: "devicon-amazonwebservices-original",
  azure: "devicon-azure-plain",
  gcp: "devicon-googlecloud-plain",
  googlecloud: "devicon-googlecloud-plain",
  heroku: "devicon-heroku-plain",
  vercel: "devicon-vercel-original",
  netlify: "devicon-netlify-plain",
  terraform: "devicon-terraform-plain",
  ansible: "devicon-ansible-original",
  jenkins: "devicon-jenkins-plain",
  githubactions: "devicon-githubactions-plain",
  nginx: "devicon-nginx-original",
  grafana: "devicon-grafana-original",
  prometheus: "devicon-prometheus-original",

  // ── Version Control / Tools ────────────────────────────────────
  git: "devicon-git-plain",
  github: "devicon-github-original",
  gitlab: "devicon-gitlab-plain",
  bitbucket: "devicon-bitbucket-original",
  postman: "devicon-postman-plain",
  npm: "devicon-npm-original-wordmark",
  yarn: "devicon-yarn-plain",
  pnpm: "devicon-pnpm-plain",
  webpack: "devicon-webpack-plain",
  vite: "devicon-vite-plain",
  vitejs: "devicon-vitejs-plain",
  turbo: "devicon-turbo-plain",

  // ── IDEs / Editors ─────────────────────────────────────────────
  vscode: "devicon-vscode-plain",
  visualstudio: "devicon-visualstudio-plain",
  intellij: "devicon-intellij-plain",
  pycharm: "devicon-pycharm-plain",
  webstorm: "devicon-webstorm-plain",
  vim: "devicon-vim-plain",
  neovim: "devicon-neovim-plain",
  emacs: "devicon-emacs-original",
  sublime: "devicon-sublime-plain",

  // ── Hardware / Embedded ────────────────────────────────────────
  arduino: "devicon-arduino-plain",
  raspberrypi: "devicon-raspberrypi-line",

  // ── Testing ────────────────────────────────────────────────────
  jest: "devicon-jest-plain",
  mocha: "devicon-mocha-plain",
  cypress: "devicon-cypressio-plain",
  playwright: "devicon-playwright-plain",
  selenium: "devicon-selenium-original",

  // ── OS ─────────────────────────────────────────────────────────
  linux: "devicon-linux-plain",
  ubuntu: "devicon-ubuntu-plain",
  debian: "devicon-debian-plain",
  centos: "devicon-centos-plain",
  redhat: "devicon-redhat-plain",
  fedora: "devicon-fedora-plain",
  archlinux: "devicon-archlinux-plain",
  windows: "devicon-windows8-original",
  macos: "devicon-apple-original",

  // ── AI / ML ────────────────────────────────────────────────────
  tensorflow: "devicon-tensorflow-original",
  pytorch: "devicon-pytorch-plain",
  keras: "devicon-keras-plain",
  scikitlearn: "devicon-scikitlearn-original",
  opencv: "devicon-opencv-plain",
  jupyter: "devicon-jupyter-plain",
  pandas: "devicon-pandas-original",
  numpy: "devicon-numpy-original",
  matplotlib: "devicon-matplotlib-original",
  colab: "devicon-googlecolab-plain",

  // ── Misc ───────────────────────────────────────────────────────
  figma: "devicon-figma-plain",
  photoshop: "devicon-photoshop-plain",
  blender: "devicon-blender-original",
  unity: "devicon-unity-original",
  unrealengine: "devicon-unrealengine-original",
  markdown: "devicon-markdown-original",
  json: "devicon-json-plain",
  xml: "devicon-xml-plain",
  yaml: "devicon-yaml-plain",
  babel: "devicon-babel-plain",
  eslint: "devicon-eslint-original",
  prettier: "devicon-prettier-plain",
  socketio: "devicon-socketio-original",
  redux: "devicon-redux-original",
};
